@startuml
'https://plantuml.com/class-diagram
class EncodingModule{
    + void encodeWithFiles() throws IOException
    + void encodeBasedOnNetworkAndDatabase() throws IOException
}
interface IDatabase{
    + int write(String inputString)
}
class MyDatabase implements IDatabase{
    - {static} MyDatabase _instance
    - {static} Map<Integer, String> _data
    - {static} int _count = 0
    - MyDatabase()
    + int write(String inputString)
    + {static}MyDatabase getInstance()
}
class EncodingModuleClient{
    + {static} void main(String[] args) throws IOException
}
EncodingModule ..> IDatabase : use
@enduml