@startuml
'https://plantuml.com/class-diagram
class Duck {
    + boolean canQuack()
    + boolean canSwim()
    + void quack()
    + void swim()
}
class ElectronicDuck extends Duck{
    - boolean _on = false
    + boolean canQuack()
    + boolean canSwim()
    + void quack()
    + void swim()
    + void _turnOn()
    + void _turnOff()
}
class Pool {
    + void run()
    - void quack(Duck... ducks)
    - void swim(Duck... ducks)
    + static void main(String[] args)
}
Pool ..> Duck : use
@enduml