@startuml
'https://plantuml.com/class-diagram
package "View" {
    class UserInfoView {
        + DisplayUserInfo()
    }
    class VaccinationRequestView {
        + DisplayVaccinationRequestForm()
    }
    class VaccinationProgressView {
        + DisplayVaccinationProgress()
    }
    class UpdateUserInfoView {
        + DisplayUserInfoForm()
    }
    class PharmaciesListView() {
        + DisplayAvailablePharmaciesList()
    }
    class UserActivity{
        - userviewModel: UserViewModel
    }
    class VaccinationActivity{
        - vaccinationViewModel: VaccinationViewModel
    }
    class PharmacyActivity(){
        - pharmacyViewModel: PharmacyViewModel
    }
}
package Model{
    class UserModel {
        - name : string
        - id : UUID
        - phoneNumber : Integer
        - cin : Integer
        - Address : string
    }
    class VaccinationRequestModel {
        - id : UUID
        - userId : UUID
        - pharmacyId : UUID
        + Status : RequestStatusEnum
    }
    class VaccinationModel {
        - id : UUID
        - vaccinationRequestId : UUID
        + date : Date
        + location : string
        + Status : VaccinationStatusEnum
    }
    class PharmacyModel {
        - id : UUID
        + name : string
        + address : string
        + phoneNumber : Integer
    }
}
package ViewModel {
    class userViewModel {
        - user: MutableLiveData<UserModel>
        + updateUserInfo()
        + retrieveUserInfo()
    }
    class VaccinationViewModel{
        - vaccinations: MutableLiveData<List<VaccinationModel>>
        + createVaccinationRequest()
        + trackVaccinationProgress()
        + changeVaccinationStatus()
    }
    class PharmacyViewModel(){
        - pharmacies: MutableLiveData<List<PharmacyModel>>
        + retrievePharmacyList()
    }
}
Enum RequestStatusEnum {
    PENDING
    ACCEPTED
    REJECTED
}
Enum VaccinationStatusEnum{
    VACCINATED
    AWAITING_VACCINATION
}
@enduml